language: java
sudo: true
dist: trusty
jdk: oraclejdk9
addons:
  apt:
    packages:
      - oracle-java9-installer
before_install:
  - chmod +x mvnw

script:
- ./mvnw clean install -B

after_success:
- bash <(curl -s https://codecov.io/bash)

deploy:
  provider: heroku
  api_key: "8adc5ee3-fb2a-4d6d-8c25-ac71ba5c00a4"
  app: johnEvento
   
    
    
