language: java
sudo: true
dist: trusty
jdk: oraclejdk9
addons:
  apt:
    packages:
      - oracle-java9-installer
  sonarcloud:
    organization: "mfgonzalez-github" # the key of the org you chose at step #3
    token:
      secure: $SONAR_TOKEN # encrypted value of your token

before_install:
  - chmod +x mvnw

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
#  - ./mvnw clean install -B

deploy:
  provider: heroku
  api_key:
    secure: "8adc5ee3-fb2a-4d6d-8c25-ac71ba5c00a4"
  app: john-evento

after_success:
- bash <(curl -s https://codecov.io/bash)


script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
